cargo-features = ["edition"]

[package]
edition = "2018"
name = "fina-codegen"
version = "0.1.0"
authors = ["Murali Mohan Rath <murali@mmrath.com>"]

[lib]
name = "fina_codegen"
proc-macro = true

[dependencies]
quote = "0.6"
syn = "0.14"
synstructure = "0.9"
proc-macro2 = "0.4"
